
name: rafaelcaldeira
recipe: drupal8
config:
  webroot: docroot
services:
  appserver:
    xdebug: false
    build_as_root:
      - echo "Run additional build commands here. Run lando rebuild after updating this file."
    overrides:
      # image: 'acquia/ads-local:lando-php-7.3-nodejs-8'
      # image: 'acquia/ads-local:lando-php-7.3-nodejs-10'
      # image: 'acquia/ads-local:lando-php-7.3-nodejs-12'
      # image: 'acquia/ads-local:lando-php-7.2-nodejs-8'
      image: 'acquia/ads-local:lando-php-7.2-nodejs-10'
      # image: 'acquia/ads-local:lando-php-7.2-nodejs-12'
      cap_add:
        - SYS_ADMIN
  phpmyadmin:
    type: phpmyadmin
